
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onlyoffice
  namespace: onlyoffice
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/onlyoffice/"
