apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: hello
spec:
  rules:
   - host: hello.lesquerra.cat
     http:
       paths:  
        - backend:
            serviceName: hello
            servicePort: 80