kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
  namespace: gngforms
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi