
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gngforms-mongo
  namespace: gngforms
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gngforms/db/"
