
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb
  namespace: nextcloud
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nextCloud/db/"
