kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi