apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"
spec:
  rules:
   - host: cloud.lesquerra.cat
     http:
      paths:
       - backend:
           serviceName: nginx
           servicePort: 80
