
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nextCloud/nc/"
