apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
  namespace: tickets
  labels:
    app: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - image: hackoviddroppletsteam/tickets-backend
          name: tickets
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: static-persistent-storage
              mountPath: /project/static
            - name: media-persistent-storage
              mountPath: /project/media
      volumes:
        - name: static-persistent-storage
          persistentVolumeClaim:
            claimName: static
        - name: media-persistent-storage
          persistentVolumeClaim:
            claimName: media
