apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
    namespace:  tickets
data:
    nginx.conf: |
        upstream django {
            server tickets:8000;
        }

        server {

            listen 80;

            location / {
                proxy_pass http://django;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_redirect off;
            }
            location /static/ {
                alias /project/static/;
            }

            location /media/ {
                alias /project/media/;
            }
        }
---

