apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  namespace:  tickets
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.0-alpine
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/ # mount nginx-conf volumn to /etc/nginx
              readOnly: true
              name: nginx-conf
              volumeMounts:
            - name: static-persistent-storage
              mountPath: /project/static
      volumes:
        - name: static-persistent-storage
          persistentVolumeClaim:
            claimName: static
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
