
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-wordpress
  namespace: wordpress
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wordpress/db/"
