kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi