
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wordpress/wp/"
