
kind: PersistentVolume
apiVersion: v1
metadata:
  name: firefly-iii-upload
  namespace: firefly-iii
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/firefly_iii/upload/"
