apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: firefly-iii
  namespace: firefly-iii
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"
spec:
  rules:
   - host: finance.lesquerra.cat
     http:
      paths:
       - backend:
           serviceName: firefly-iii
           servicePort: 8080
  tls:
    - hosts:
      - finance.lesquerra.cat
      secretName: tlssecret